
services:
  backend1:
    build: ./jpaprac
    container_name: spring-backend-1
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
      - oracle-db
    networks:
      - chatnet

  backend2:
    build: ./jpaprac
    container_name: spring-backend-2
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
      - oracle-db
    networks:
      - chatnet

  backend3:
    build: ./jpaprac
    container_name: spring-backend-3
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
      - oracle-db
    networks:
      - chatnet

  frontend:
    build: ./reactprac
    container_name: react-frontend
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - chatnet

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - chatnet

  oracle-db:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
    networks:
      - chatnet

  nginx:
    image: nginx:stable
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./reactprac/build:/usr/share/nginx/html:ro # React 빌드 파일 마운트
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend1
      - backend2
      - backend3
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge
